RepositoryPattern/Models/Library.cs
using System;
using System.Collections.Generic;

namespace LibraryManagementSystemApp.Models;

public partial class Library
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? City { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}

RepositoryPattern/Controllers/LibraryController.cs
using LibraryManagementSystemApp.BO;
using LibraryManagementSystemApp.Models;
using LibraryManagementSystemApp.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Web;

namespace LibraryManagementSystemApp.Controllers
{
    public class LibraryController : Controller
    {
        private LibraryBO _libraryBO = null;
        private ILibraryRepository _libraryRepository = null;

        public LibraryController(ILibraryRepository libraryRepository)
        {
            _libraryRepository = libraryRepository;
            _libraryBO = new LibraryBO(libraryRepository);
        }
        // GET: LibraryController
        public ActionResult Index()
        {
            IEnumerable<Library> libraryList = _libraryBO.GetAllLibraries();
            return View("Views/Library/LibraryList.cshtml", libraryList);
        }

        // GET: LibraryController/Details/5
        public ActionResult Details(int id)
        {
            Library l = _libraryBO.GetLibraryById(id);
            return View("Views/Library/Details.cshtml", l);
        }

        // GET: LibraryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LibraryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Library lib)
        {
            Console.WriteLine("Create Method trigerred{0}", lib);
            int id = _libraryBO.InsertLibrary(lib);
            Console.WriteLine("Library created with id{0}", id);
            if (id > 0)
            {
                ViewData["Response"] = "Library Added Successfully";
            }
            else
            {
                ViewData["Response"] = "Library Failed to Add..";
            }
            return View("Views/Library/Create.cshtml", lib);

        }

        // GET: LibraryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LibraryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Library lib)
        {
            Console.WriteLine("Create Method trigerred{0}", lib);
            int id = _libraryBO.UpdateLibrary(lib);
            Console.WriteLine("Library created with id{0}", id);
            if (id > 0)
            {
                ViewData["Response"] = "Library Updated Successfully";
            }
            else
            {
                ViewData["Response"] = "Library Failed to update..";
            }
            return View("Views/Library/Edit.cshtml", lib);
        }

        // GET: LibraryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LibraryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // GET: LibraryController/LibraryBooks
        public ActionResult LibraryBooks()
        {
            IEnumerable<Library> libraryList = _libraryBO.GetAllLibrariesUsingJoins();
            return View("Views/Library/LibraryBooks.cshtml", libraryList);
        }

        // GET: LibraryController/LibraryWithFilter
        
        public ActionResult LibraryFilterByName()
        {
            IEnumerable<Library> l = _libraryBO.GetLibraryByNameAndCity();
            return View("Views/Library/ListView.cshtml", l);

        }

       
        public ActionResult LibraryJoinBook(string libraryName,string bookAuthor)
        {
           /* 
            if (libraryName == null)
            {
                libraryName = "";
            }
            if (bookAuthor == null)
            {
                bookAuthor = "";
            }*/

            var lib = _libraryBO.GetLibraryBookUsingJoin(libraryName,bookAuthor);
            return View("Views/Library/LibraryJoinBook.cshtml",lib);
        }
    }
}

RepositoryPattern/Views/Library/Create.cshtml
@model LibraryManagementSystemApp.Models.Library



<h4>Library</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepositoryPattern/Views/Library/Details.cshtml
@model LibraryManagementSystemApp.Models.Library

<div>
    <h4>Library</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RepositoryPattern/Views/Library/Edit.cshtml
@model LibraryManagementSystemApp.Models.Library

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Library</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepositoryPattern/Views/Library/LibraryBooks.cshtml
@model IEnumerable<LibraryManagementSystemApp.Models.Library>


@{
    ViewData["Title"] = "LibraryBooks";
}

<h1>LibraryBooks</h1>

<table class="table">
   

    <thead>
        <tr>
            <th>Library Name</th>
            <th>City</th>
            <th>Book ID</th>
            <th>Book Name</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
            @foreach (var library in Model)
            {
                    <tr>
                        <td>@library.Name</td>
                        <td>@library.City</td>

                        <td></td>
                        <td></td>
                    </tr>
                @foreach (var item in library.Books)
                {
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td>@item.Bookid</td>
                                    <td>@item.Bookname</td>
                                    <td>@item.Author</td>
                                </tr>
                }



            }
    </tbody>
</table>

RepositoryPattern/Views/Library/LibraryJoinBook.cshtml
@model IEnumerable<LibraryManagementSystemApp.Models.Library>

@{
    ViewData["Title"] = "LibraryJoinBook";
}

<h1>LibraryJoinBook</h1>

@using (Html.BeginForm("LibraryJoinBook", "Library", FormMethod.Get))
{
    @Html.TextBox("libraryName", null, new { placeholder = "Enter your value" })
    @Html.TextBox("bookAuthor", null, new { placeholder = "Enter your value" })
        <button type="submit">Submit</button>
}




<table class="table">


    <thead>
        <tr>
            <th>Library Name</th>
            <th>City</th>
            <th>Book Name</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
       
        @foreach (var library in Model)
        {
            @foreach (var item in library.Books)
            {
                               <tr>
                                    <td>@library.Name</td>
                                    <td>@library.City</td>
                                    <td>@item.Bookname</td>
                                    <td>@item.Author</td>
                                    </tr>

            }     


        }
        



        
    </tbody>
</table>

RepositoryPattern/Views/Library/LibraryList.cshtml
@model IEnumerable<LibraryManagementSystemApp.Models.Library>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RepositoryPattern/Views/Library/ListView.cshtml
@model IEnumerable<LibraryManagementSystemApp.Models.Library>


@{
    ViewData["Title"] = "ListView";
}

<h1>ListView</h1>

<table class="table">
   
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            
        </tr>
}
    </tbody>
    
</table>

<div>
    <a asp-action="Index">Back to List</a>
</div>